"""Domain models package — re-exports from models for backward compatibility."""
from mailagent.domain.models import (  # noqa: F401
    ApprovalRequest,
    CalibrationLog,
    ClassificationMeta,
    ClassificationResponse,
    ClassificationVersions,
    CreateRunRequest,
    Decision,
    EnrichmentError,
    FusionMeta,
    MailEvent,
    NormalizedSubject,
    PathBCandidate,
    PathBResult,
    ProposedAction,
    RuleMatch,
    RuleResult,
    RunResponse,
    RunStatus,
    SampleQualityAssessment,
    SampleRecord,
    SkillDefinition,
    SkillVersion,
    TaxonomyLabel,
    ThreadSegment,
)
